env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.eslint.json
plugins:
  - '@typescript-eslint'
rules:
  import/no-import-module-exports: off
