version: '3'
services:
  app:
    container_name: monitor-rpi
    build:
      args:
        - USER_NAME
        - USER_ID
        - GROUP_NAME
        - GROUP_ID
    tty: true
    volumes:
      - ./:/mnt/work
    ports:
      - 3000:3000
      - 3001:3001
