env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.eslint.json
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/no-import-module-exports: off
  comma-dangle: off
  '@typescript-eslint/comma-dangle':
    - error
    - never
  react/function-component-definition:
    - error
    - { namedComponents: arrow-function, unnamedComponents: arrow-function }
  arrow-body-style:
    - off
